package contraption

// Code generated by peg regexp.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleBody
	ruleAlter
	ruleCat
	rulePoint
	ruleConcrete
	ruleAny
	ruleSeveral
	ruleMaybe
	ruleLazyAny
	ruleLazySeveral
	ruleLazyMaybe
	ruleType
	ruleValue
	ruleRect
	ruleIn
	ruleOut
	ruleTime
	ruleBegin
	ruleEnd
	ruleToken
	ruleNumber
	ruleChar
	ruleSP
)

var rul3s = [...]string{
	"Unknown",
	"Body",
	"Alter",
	"Cat",
	"Point",
	"Concrete",
	"Any",
	"Several",
	"Maybe",
	"LazyAny",
	"LazySeveral",
	"LazyMaybe",
	"Type",
	"Value",
	"Rect",
	"In",
	"Out",
	"Time",
	"Begin",
	"End",
	"Token",
	"Number",
	"Char",
	"SP",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type rpeg struct {
	typs  map[string]any
	Type  string
	Value string
	Begin bool
	End   bool
	In    bool

	Buffer string
	buffer []rune
	rules  [24]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *rpeg) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *rpeg) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *rpeg
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *rpeg) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *rpeg) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *rpeg) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*rpeg) error {
	return func(p *rpeg) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*rpeg) error {
	return func(p *rpeg) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *rpeg) Init(options ...func(*rpeg) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Body <- <(Alter / Cat)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2, tokenIndex2 := position, tokenIndex
					if !_rules[ruleAlter]() {
						goto l3
					}
					goto l2
				l3:
					position, tokenIndex = position2, tokenIndex2
					if !_rules[ruleCat]() {
						goto l0
					}
				}
			l2:
				add(ruleBody, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Alter <- <((Cat (' ' / '\t' / '\n')* '|' (' ' / '\t' / '\n')* Cat) / (Cat (' ' / '\t' / '\n')* '|' (' ' / '\t' / '\n')* Alter))> */
		func() bool {
			position4, tokenIndex4 := position, tokenIndex
			{
				position5 := position
				{
					position6, tokenIndex6 := position, tokenIndex
					if !_rules[ruleCat]() {
						goto l7
					}
				l8:
					{
						position9, tokenIndex9 := position, tokenIndex
						{
							position10, tokenIndex10 := position, tokenIndex
							if buffer[position] != rune(' ') {
								goto l11
							}
							position++
							goto l10
						l11:
							position, tokenIndex = position10, tokenIndex10
							if buffer[position] != rune('\t') {
								goto l12
							}
							position++
							goto l10
						l12:
							position, tokenIndex = position10, tokenIndex10
							if buffer[position] != rune('\n') {
								goto l9
							}
							position++
						}
					l10:
						goto l8
					l9:
						position, tokenIndex = position9, tokenIndex9
					}
					if buffer[position] != rune('|') {
						goto l7
					}
					position++
				l13:
					{
						position14, tokenIndex14 := position, tokenIndex
						{
							position15, tokenIndex15 := position, tokenIndex
							if buffer[position] != rune(' ') {
								goto l16
							}
							position++
							goto l15
						l16:
							position, tokenIndex = position15, tokenIndex15
							if buffer[position] != rune('\t') {
								goto l17
							}
							position++
							goto l15
						l17:
							position, tokenIndex = position15, tokenIndex15
							if buffer[position] != rune('\n') {
								goto l14
							}
							position++
						}
					l15:
						goto l13
					l14:
						position, tokenIndex = position14, tokenIndex14
					}
					if !_rules[ruleCat]() {
						goto l7
					}
					goto l6
				l7:
					position, tokenIndex = position6, tokenIndex6
					if !_rules[ruleCat]() {
						goto l4
					}
				l18:
					{
						position19, tokenIndex19 := position, tokenIndex
						{
							position20, tokenIndex20 := position, tokenIndex
							if buffer[position] != rune(' ') {
								goto l21
							}
							position++
							goto l20
						l21:
							position, tokenIndex = position20, tokenIndex20
							if buffer[position] != rune('\t') {
								goto l22
							}
							position++
							goto l20
						l22:
							position, tokenIndex = position20, tokenIndex20
							if buffer[position] != rune('\n') {
								goto l19
							}
							position++
						}
					l20:
						goto l18
					l19:
						position, tokenIndex = position19, tokenIndex19
					}
					if buffer[position] != rune('|') {
						goto l4
					}
					position++
				l23:
					{
						position24, tokenIndex24 := position, tokenIndex
						{
							position25, tokenIndex25 := position, tokenIndex
							if buffer[position] != rune(' ') {
								goto l26
							}
							position++
							goto l25
						l26:
							position, tokenIndex = position25, tokenIndex25
							if buffer[position] != rune('\t') {
								goto l27
							}
							position++
							goto l25
						l27:
							position, tokenIndex = position25, tokenIndex25
							if buffer[position] != rune('\n') {
								goto l24
							}
							position++
						}
					l25:
						goto l23
					l24:
						position, tokenIndex = position24, tokenIndex24
					}
					if !_rules[ruleAlter]() {
						goto l4
					}
				}
			l6:
				add(ruleAlter, position5)
			}
			return true
		l4:
			position, tokenIndex = position4, tokenIndex4
			return false
		},
		/* 2 Cat <- <(Point ((' ' / '\t' / '\n')* Cat)?)> */
		func() bool {
			position28, tokenIndex28 := position, tokenIndex
			{
				position29 := position
				if !_rules[rulePoint]() {
					goto l28
				}
				{
					position30, tokenIndex30 := position, tokenIndex
				l32:
					{
						position33, tokenIndex33 := position, tokenIndex
						{
							position34, tokenIndex34 := position, tokenIndex
							if buffer[position] != rune(' ') {
								goto l35
							}
							position++
							goto l34
						l35:
							position, tokenIndex = position34, tokenIndex34
							if buffer[position] != rune('\t') {
								goto l36
							}
							position++
							goto l34
						l36:
							position, tokenIndex = position34, tokenIndex34
							if buffer[position] != rune('\n') {
								goto l33
							}
							position++
						}
					l34:
						goto l32
					l33:
						position, tokenIndex = position33, tokenIndex33
					}
					if !_rules[ruleCat]() {
						goto l30
					}
					goto l31
				l30:
					position, tokenIndex = position30, tokenIndex30
				}
			l31:
				add(ruleCat, position29)
			}
			return true
		l28:
			position, tokenIndex = position28, tokenIndex28
			return false
		},
		/* 3 Point <- <(Concrete (Any / Several / Maybe / LazyAny / LazySeveral / LazyMaybe)?)> */
		func() bool {
			position37, tokenIndex37 := position, tokenIndex
			{
				position38 := position
				if !_rules[ruleConcrete]() {
					goto l37
				}
				{
					position39, tokenIndex39 := position, tokenIndex
					{
						position41, tokenIndex41 := position, tokenIndex
						if !_rules[ruleAny]() {
							goto l42
						}
						goto l41
					l42:
						position, tokenIndex = position41, tokenIndex41
						if !_rules[ruleSeveral]() {
							goto l43
						}
						goto l41
					l43:
						position, tokenIndex = position41, tokenIndex41
						if !_rules[ruleMaybe]() {
							goto l44
						}
						goto l41
					l44:
						position, tokenIndex = position41, tokenIndex41
						if !_rules[ruleLazyAny]() {
							goto l45
						}
						goto l41
					l45:
						position, tokenIndex = position41, tokenIndex41
						if !_rules[ruleLazySeveral]() {
							goto l46
						}
						goto l41
					l46:
						position, tokenIndex = position41, tokenIndex41
						if !_rules[ruleLazyMaybe]() {
							goto l39
						}
					}
				l41:
					goto l40
				l39:
					position, tokenIndex = position39, tokenIndex39
				}
			l40:
				add(rulePoint, position38)
			}
			return true
		l37:
			position, tokenIndex = position37, tokenIndex37
			return false
		},
		/* 4 Concrete <- <(Type ('(' SP Value SP ')')? ((Rect Time?) / (Time? Rect?)))> */
		func() bool {
			position47, tokenIndex47 := position, tokenIndex
			{
				position48 := position
				if !_rules[ruleType]() {
					goto l47
				}
				{
					position49, tokenIndex49 := position, tokenIndex
					if buffer[position] != rune('(') {
						goto l49
					}
					position++
					if !_rules[ruleSP]() {
						goto l49
					}
					if !_rules[ruleValue]() {
						goto l49
					}
					if !_rules[ruleSP]() {
						goto l49
					}
					if buffer[position] != rune(')') {
						goto l49
					}
					position++
					goto l50
				l49:
					position, tokenIndex = position49, tokenIndex49
				}
			l50:
				{
					position51, tokenIndex51 := position, tokenIndex
					if !_rules[ruleRect]() {
						goto l52
					}
					{
						position53, tokenIndex53 := position, tokenIndex
						if !_rules[ruleTime]() {
							goto l53
						}
						goto l54
					l53:
						position, tokenIndex = position53, tokenIndex53
					}
				l54:
					goto l51
				l52:
					position, tokenIndex = position51, tokenIndex51
					{
						position55, tokenIndex55 := position, tokenIndex
						if !_rules[ruleTime]() {
							goto l55
						}
						goto l56
					l55:
						position, tokenIndex = position55, tokenIndex55
					}
				l56:
					{
						position57, tokenIndex57 := position, tokenIndex
						if !_rules[ruleRect]() {
							goto l57
						}
						goto l58
					l57:
						position, tokenIndex = position57, tokenIndex57
					}
				l58:
				}
			l51:
				add(ruleConcrete, position48)
			}
			return true
		l47:
			position, tokenIndex = position47, tokenIndex47
			return false
		},
		/* 5 Any <- <'*'> */
		func() bool {
			position59, tokenIndex59 := position, tokenIndex
			{
				position60 := position
				if buffer[position] != rune('*') {
					goto l59
				}
				position++
				add(ruleAny, position60)
			}
			return true
		l59:
			position, tokenIndex = position59, tokenIndex59
			return false
		},
		/* 6 Several <- <'+'> */
		func() bool {
			position61, tokenIndex61 := position, tokenIndex
			{
				position62 := position
				if buffer[position] != rune('+') {
					goto l61
				}
				position++
				add(ruleSeveral, position62)
			}
			return true
		l61:
			position, tokenIndex = position61, tokenIndex61
			return false
		},
		/* 7 Maybe <- <'?'> */
		func() bool {
			position63, tokenIndex63 := position, tokenIndex
			{
				position64 := position
				if buffer[position] != rune('?') {
					goto l63
				}
				position++
				add(ruleMaybe, position64)
			}
			return true
		l63:
			position, tokenIndex = position63, tokenIndex63
			return false
		},
		/* 8 LazyAny <- <('*' '?')> */
		func() bool {
			position65, tokenIndex65 := position, tokenIndex
			{
				position66 := position
				if buffer[position] != rune('*') {
					goto l65
				}
				position++
				if buffer[position] != rune('?') {
					goto l65
				}
				position++
				add(ruleLazyAny, position66)
			}
			return true
		l65:
			position, tokenIndex = position65, tokenIndex65
			return false
		},
		/* 9 LazySeveral <- <('+' '?')> */
		func() bool {
			position67, tokenIndex67 := position, tokenIndex
			{
				position68 := position
				if buffer[position] != rune('+') {
					goto l67
				}
				position++
				if buffer[position] != rune('?') {
					goto l67
				}
				position++
				add(ruleLazySeveral, position68)
			}
			return true
		l67:
			position, tokenIndex = position67, tokenIndex67
			return false
		},
		/* 10 LazyMaybe <- <('?' '?')> */
		func() bool {
			position69, tokenIndex69 := position, tokenIndex
			{
				position70 := position
				if buffer[position] != rune('?') {
					goto l69
				}
				position++
				if buffer[position] != rune('?') {
					goto l69
				}
				position++
				add(ruleLazyMaybe, position70)
			}
			return true
		l69:
			position, tokenIndex = position69, tokenIndex69
			return false
		},
		/* 11 Type <- <Token> */
		func() bool {
			position71, tokenIndex71 := position, tokenIndex
			{
				position72 := position
				if !_rules[ruleToken]() {
					goto l71
				}
				add(ruleType, position72)
			}
			return true
		l71:
			position, tokenIndex = position71, tokenIndex71
			return false
		},
		/* 12 Value <- <(Number / Char / Token)> */
		func() bool {
			position73, tokenIndex73 := position, tokenIndex
			{
				position74 := position
				{
					position75, tokenIndex75 := position, tokenIndex
					if !_rules[ruleNumber]() {
						goto l76
					}
					goto l75
				l76:
					position, tokenIndex = position75, tokenIndex75
					if !_rules[ruleChar]() {
						goto l77
					}
					goto l75
				l77:
					position, tokenIndex = position75, tokenIndex75
					if !_rules[ruleToken]() {
						goto l73
					}
				}
			l75:
				add(ruleValue, position74)
			}
			return true
		l73:
			position, tokenIndex = position73, tokenIndex73
			return false
		},
		/* 13 Rect <- <(In / Out)> */
		func() bool {
			position78, tokenIndex78 := position, tokenIndex
			{
				position79 := position
				{
					position80, tokenIndex80 := position, tokenIndex
					if !_rules[ruleIn]() {
						goto l81
					}
					goto l80
				l81:
					position, tokenIndex = position80, tokenIndex80
					if !_rules[ruleOut]() {
						goto l78
					}
				}
			l80:
				add(ruleRect, position79)
			}
			return true
		l78:
			position, tokenIndex = position78, tokenIndex78
			return false
		},
		/* 14 In <- <(':' 'i' 'n')> */
		func() bool {
			position82, tokenIndex82 := position, tokenIndex
			{
				position83 := position
				if buffer[position] != rune(':') {
					goto l82
				}
				position++
				if buffer[position] != rune('i') {
					goto l82
				}
				position++
				if buffer[position] != rune('n') {
					goto l82
				}
				position++
				add(ruleIn, position83)
			}
			return true
		l82:
			position, tokenIndex = position82, tokenIndex82
			return false
		},
		/* 15 Out <- <(':' 'o' 'u' 't')> */
		func() bool {
			position84, tokenIndex84 := position, tokenIndex
			{
				position85 := position
				if buffer[position] != rune(':') {
					goto l84
				}
				position++
				if buffer[position] != rune('o') {
					goto l84
				}
				position++
				if buffer[position] != rune('u') {
					goto l84
				}
				position++
				if buffer[position] != rune('t') {
					goto l84
				}
				position++
				add(ruleOut, position85)
			}
			return true
		l84:
			position, tokenIndex = position84, tokenIndex84
			return false
		},
		/* 16 Time <- <(Begin / End)> */
		func() bool {
			position86, tokenIndex86 := position, tokenIndex
			{
				position87 := position
				{
					position88, tokenIndex88 := position, tokenIndex
					if !_rules[ruleBegin]() {
						goto l89
					}
					goto l88
				l89:
					position, tokenIndex = position88, tokenIndex88
					if !_rules[ruleEnd]() {
						goto l86
					}
				}
			l88:
				add(ruleTime, position87)
			}
			return true
		l86:
			position, tokenIndex = position86, tokenIndex86
			return false
		},
		/* 17 Begin <- <(':' 'b' 'e' 'g' 'i' 'n')> */
		func() bool {
			position90, tokenIndex90 := position, tokenIndex
			{
				position91 := position
				if buffer[position] != rune(':') {
					goto l90
				}
				position++
				if buffer[position] != rune('b') {
					goto l90
				}
				position++
				if buffer[position] != rune('e') {
					goto l90
				}
				position++
				if buffer[position] != rune('g') {
					goto l90
				}
				position++
				if buffer[position] != rune('i') {
					goto l90
				}
				position++
				if buffer[position] != rune('n') {
					goto l90
				}
				position++
				add(ruleBegin, position91)
			}
			return true
		l90:
			position, tokenIndex = position90, tokenIndex90
			return false
		},
		/* 18 End <- <(':' 'e' 'n' 'd')> */
		func() bool {
			position92, tokenIndex92 := position, tokenIndex
			{
				position93 := position
				if buffer[position] != rune(':') {
					goto l92
				}
				position++
				if buffer[position] != rune('e') {
					goto l92
				}
				position++
				if buffer[position] != rune('n') {
					goto l92
				}
				position++
				if buffer[position] != rune('d') {
					goto l92
				}
				position++
				add(ruleEnd, position93)
			}
			return true
		l92:
			position, tokenIndex = position92, tokenIndex92
			return false
		},
		/* 19 Token <- <(('!'? ('_' / [a-z] / [A-Z]) ('_' / [a-z] / [A-Z] / [0-9] / '/' / '.' / '-')*) / '←' / '→' / '↑' / '↓' / '.')> */
		func() bool {
			position94, tokenIndex94 := position, tokenIndex
			{
				position95 := position
				{
					position96, tokenIndex96 := position, tokenIndex
					{
						position98, tokenIndex98 := position, tokenIndex
						if buffer[position] != rune('!') {
							goto l98
						}
						position++
						goto l99
					l98:
						position, tokenIndex = position98, tokenIndex98
					}
				l99:
					{
						position100, tokenIndex100 := position, tokenIndex
						if buffer[position] != rune('_') {
							goto l101
						}
						position++
						goto l100
					l101:
						position, tokenIndex = position100, tokenIndex100
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l102
						}
						position++
						goto l100
					l102:
						position, tokenIndex = position100, tokenIndex100
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l97
						}
						position++
					}
				l100:
				l103:
					{
						position104, tokenIndex104 := position, tokenIndex
						{
							position105, tokenIndex105 := position, tokenIndex
							if buffer[position] != rune('_') {
								goto l106
							}
							position++
							goto l105
						l106:
							position, tokenIndex = position105, tokenIndex105
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l107
							}
							position++
							goto l105
						l107:
							position, tokenIndex = position105, tokenIndex105
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l108
							}
							position++
							goto l105
						l108:
							position, tokenIndex = position105, tokenIndex105
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l109
							}
							position++
							goto l105
						l109:
							position, tokenIndex = position105, tokenIndex105
							if buffer[position] != rune('/') {
								goto l110
							}
							position++
							goto l105
						l110:
							position, tokenIndex = position105, tokenIndex105
							if buffer[position] != rune('.') {
								goto l111
							}
							position++
							goto l105
						l111:
							position, tokenIndex = position105, tokenIndex105
							if buffer[position] != rune('-') {
								goto l104
							}
							position++
						}
					l105:
						goto l103
					l104:
						position, tokenIndex = position104, tokenIndex104
					}
					goto l96
				l97:
					position, tokenIndex = position96, tokenIndex96
					if buffer[position] != rune('←') {
						goto l112
					}
					position++
					goto l96
				l112:
					position, tokenIndex = position96, tokenIndex96
					if buffer[position] != rune('→') {
						goto l113
					}
					position++
					goto l96
				l113:
					position, tokenIndex = position96, tokenIndex96
					if buffer[position] != rune('↑') {
						goto l114
					}
					position++
					goto l96
				l114:
					position, tokenIndex = position96, tokenIndex96
					if buffer[position] != rune('↓') {
						goto l115
					}
					position++
					goto l96
				l115:
					position, tokenIndex = position96, tokenIndex96
					if buffer[position] != rune('.') {
						goto l94
					}
					position++
				}
			l96:
				add(ruleToken, position95)
			}
			return true
		l94:
			position, tokenIndex = position94, tokenIndex94
			return false
		},
		/* 20 Number <- <(('-' / '+')? [0-9] ('o' / 'O' / 'x' / 'X')? [0-9]*)> */
		func() bool {
			position116, tokenIndex116 := position, tokenIndex
			{
				position117 := position
				{
					position118, tokenIndex118 := position, tokenIndex
					{
						position120, tokenIndex120 := position, tokenIndex
						if buffer[position] != rune('-') {
							goto l121
						}
						position++
						goto l120
					l121:
						position, tokenIndex = position120, tokenIndex120
						if buffer[position] != rune('+') {
							goto l118
						}
						position++
					}
				l120:
					goto l119
				l118:
					position, tokenIndex = position118, tokenIndex118
				}
			l119:
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l116
				}
				position++
				{
					position122, tokenIndex122 := position, tokenIndex
					{
						position124, tokenIndex124 := position, tokenIndex
						if buffer[position] != rune('o') {
							goto l125
						}
						position++
						goto l124
					l125:
						position, tokenIndex = position124, tokenIndex124
						if buffer[position] != rune('O') {
							goto l126
						}
						position++
						goto l124
					l126:
						position, tokenIndex = position124, tokenIndex124
						if buffer[position] != rune('x') {
							goto l127
						}
						position++
						goto l124
					l127:
						position, tokenIndex = position124, tokenIndex124
						if buffer[position] != rune('X') {
							goto l122
						}
						position++
					}
				l124:
					goto l123
				l122:
					position, tokenIndex = position122, tokenIndex122
				}
			l123:
			l128:
				{
					position129, tokenIndex129 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l129
					}
					position++
					goto l128
				l129:
					position, tokenIndex = position129, tokenIndex129
				}
				add(ruleNumber, position117)
			}
			return true
		l116:
			position, tokenIndex = position116, tokenIndex116
			return false
		},
		/* 21 Char <- <('\'' . '\'')> */
		func() bool {
			position130, tokenIndex130 := position, tokenIndex
			{
				position131 := position
				if buffer[position] != rune('\'') {
					goto l130
				}
				position++
				if !matchDot() {
					goto l130
				}
				if buffer[position] != rune('\'') {
					goto l130
				}
				position++
				add(ruleChar, position131)
			}
			return true
		l130:
			position, tokenIndex = position130, tokenIndex130
			return false
		},
		/* 22 SP <- <(' ' / '\t' / '\n')*> */
		func() bool {
			{
				position133 := position
			l134:
				{
					position135, tokenIndex135 := position, tokenIndex
					{
						position136, tokenIndex136 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l137
						}
						position++
						goto l136
					l137:
						position, tokenIndex = position136, tokenIndex136
						if buffer[position] != rune('\t') {
							goto l138
						}
						position++
						goto l136
					l138:
						position, tokenIndex = position136, tokenIndex136
						if buffer[position] != rune('\n') {
							goto l135
						}
						position++
					}
				l136:
					goto l134
				l135:
					position, tokenIndex = position135, tokenIndex135
				}
				add(ruleSP, position133)
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
